import NavbarComponent from "@/components/navbar/NavbarComponent";
import "./globals.css";
import { Alegreya } from "next/font/google";
import FooterComponent from "@/components/footer/FooterComponent";

const algreya = Alegreya({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${algreya.className}`}>
        <div className="min-h-screen flex flex-col justify-between">
          <NavbarComponent />
          <div className="w-full  md:max-w-[1366px] my-0 mx-auto py-0 px-6 md:px-[60px] flex-1">
            {children}
          </div>
          <FooterComponent />
        </div>
      </body>
    </html>
  );
}
